/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardrobesRouteImport } from './routes/wardrobes'
import { Route as WardrobeAccessoriesRouteImport } from './routes/wardrobe-accessories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchensRouteImport } from './routes/kitchens'
import { Route as KitchenAppliancesRouteImport } from './routes/kitchen-appliances'
import { Route as KitchenAccessoriesRouteImport } from './routes/kitchen-accessories'
import { Route as InteriorsRouteImport } from './routes/interiors'
import { Route as HomeFurnituresRouteImport } from './routes/home-furnitures'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DoorsRouteImport } from './routes/doors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WardrobesIndexRouteImport } from './routes/wardrobes.index'
import { Route as KitchensIndexRouteImport } from './routes/kitchens.index'
import { Route as KitchenAppliancesIndexRouteImport } from './routes/kitchen-appliances.index'
import { Route as InteriorsIndexRouteImport } from './routes/interiors.index'
import { Route as HomeFurnituresIndexRouteImport } from './routes/home-furnitures.index'
import { Route as DoorsIndexRouteImport } from './routes/doors.index'
import { Route as WardrobesWardrobeRouteImport } from './routes/wardrobes.wardrobe'
import { Route as WardrobesWalkInClosetRouteImport } from './routes/wardrobes.walk-in-closet'
import { Route as WardrobesClassicWardrobeRouteImport } from './routes/wardrobes.classic-wardrobe'
import { Route as WardrobesAluminiumWardrobeRouteImport } from './routes/wardrobes.aluminium-wardrobe'
import { Route as KitchensModularKitchenRouteImport } from './routes/kitchens.modular-kitchen'
import { Route as KitchensModernKitchenRouteImport } from './routes/kitchens.modern-kitchen'
import { Route as KitchensClassicKitchenRouteImport } from './routes/kitchens.classic-kitchen'
import { Route as KitchenAppliancesVattiRouteImport } from './routes/kitchen-appliances.vatti'
import { Route as KitchenAppliancesRobamRouteImport } from './routes/kitchen-appliances.robam'
import { Route as KitchenAppliancesFotileRouteImport } from './routes/kitchen-appliances.fotile'
import { Route as KitchenAppliancesBoschRouteImport } from './routes/kitchen-appliances.bosch'
import { Route as InteriorsWoodenFlooringRouteImport } from './routes/interiors.wooden-flooring'
import { Route as InteriorsMediaWallsRouteImport } from './routes/interiors.media-walls'
import { Route as InteriorsFeatureWallsRouteImport } from './routes/interiors.feature-walls'
import { Route as InteriorsBedWallsRouteImport } from './routes/interiors.bed-walls'
import { Route as HomeFurnituresWoodenRouteImport } from './routes/home-furnitures.wooden'
import { Route as HomeFurnituresLaminatedRouteImport } from './routes/home-furnitures.laminated'
import { Route as HomeFurnituresCushionRouteImport } from './routes/home-furnitures.cushion'
import { Route as DoorsSlidingDoorsRouteImport } from './routes/doors.sliding-doors'
import { Route as DoorsMainDoorsRouteImport } from './routes/doors.main-doors'
import { Route as DoorsEngineeredDoorsRouteImport } from './routes/doors.engineered-doors'
import { Route as DoorsBedBathroomDoorsRouteImport } from './routes/doors.bed-bathroom-doors'
import { Route as DesignSubcategoryProductRouteImport } from './routes/design.$subcategory.$product'
import { Route as ApiPublicAdminBootstrapRouteImport } from './routes/api.public.admin-bootstrap'
import { Route as ApiPublicSiteImageSplatRouteImport } from './routes/api.public.site-image.$'

const WardrobesRoute = WardrobesRouteImport.update({
  id: '/wardrobes',
  path: '/wardrobes',
  getParentRoute: () => rootRouteImport,
} as any)
const WardrobeAccessoriesRoute = WardrobeAccessoriesRouteImport.update({
  id: '/wardrobe-accessories',
  path: '/wardrobe-accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchensRoute = KitchensRouteImport.update({
  id: '/kitchens',
  path: '/kitchens',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenAppliancesRoute = KitchenAppliancesRouteImport.update({
  id: '/kitchen-appliances',
  path: '/kitchen-appliances',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenAccessoriesRoute = KitchenAccessoriesRouteImport.update({
  id: '/kitchen-accessories',
  path: '/kitchen-accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorsRoute = InteriorsRouteImport.update({
  id: '/interiors',
  path: '/interiors',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeFurnituresRoute = HomeFurnituresRouteImport.update({
  id: '/home-furnitures',
  path: '/home-furnitures',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DoorsRoute = DoorsRouteImport.update({
  id: '/doors',
  path: '/doors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WardrobesIndexRoute = WardrobesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WardrobesRoute,
} as any)
const KitchensIndexRoute = KitchensIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KitchensRoute,
} as any)
const KitchenAppliancesIndexRoute = KitchenAppliancesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KitchenAppliancesRoute,
} as any)
const InteriorsIndexRoute = InteriorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InteriorsRoute,
} as any)
const HomeFurnituresIndexRoute = HomeFurnituresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeFurnituresRoute,
} as any)
const DoorsIndexRoute = DoorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoorsRoute,
} as any)
const WardrobesWardrobeRoute = WardrobesWardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => WardrobesRoute,
} as any)
const WardrobesWalkInClosetRoute = WardrobesWalkInClosetRouteImport.update({
  id: '/walk-in-closet',
  path: '/walk-in-closet',
  getParentRoute: () => WardrobesRoute,
} as any)
const WardrobesClassicWardrobeRoute =
  WardrobesClassicWardrobeRouteImport.update({
    id: '/classic-wardrobe',
    path: '/classic-wardrobe',
    getParentRoute: () => WardrobesRoute,
  } as any)
const WardrobesAluminiumWardrobeRoute =
  WardrobesAluminiumWardrobeRouteImport.update({
    id: '/aluminium-wardrobe',
    path: '/aluminium-wardrobe',
    getParentRoute: () => WardrobesRoute,
  } as any)
const KitchensModularKitchenRoute = KitchensModularKitchenRouteImport.update({
  id: '/modular-kitchen',
  path: '/modular-kitchen',
  getParentRoute: () => KitchensRoute,
} as any)
const KitchensModernKitchenRoute = KitchensModernKitchenRouteImport.update({
  id: '/modern-kitchen',
  path: '/modern-kitchen',
  getParentRoute: () => KitchensRoute,
} as any)
const KitchensClassicKitchenRoute = KitchensClassicKitchenRouteImport.update({
  id: '/classic-kitchen',
  path: '/classic-kitchen',
  getParentRoute: () => KitchensRoute,
} as any)
const KitchenAppliancesVattiRoute = KitchenAppliancesVattiRouteImport.update({
  id: '/vatti',
  path: '/vatti',
  getParentRoute: () => KitchenAppliancesRoute,
} as any)
const KitchenAppliancesRobamRoute = KitchenAppliancesRobamRouteImport.update({
  id: '/robam',
  path: '/robam',
  getParentRoute: () => KitchenAppliancesRoute,
} as any)
const KitchenAppliancesFotileRoute = KitchenAppliancesFotileRouteImport.update({
  id: '/fotile',
  path: '/fotile',
  getParentRoute: () => KitchenAppliancesRoute,
} as any)
const KitchenAppliancesBoschRoute = KitchenAppliancesBoschRouteImport.update({
  id: '/bosch',
  path: '/bosch',
  getParentRoute: () => KitchenAppliancesRoute,
} as any)
const InteriorsWoodenFlooringRoute = InteriorsWoodenFlooringRouteImport.update({
  id: '/wooden-flooring',
  path: '/wooden-flooring',
  getParentRoute: () => InteriorsRoute,
} as any)
const InteriorsMediaWallsRoute = InteriorsMediaWallsRouteImport.update({
  id: '/media-walls',
  path: '/media-walls',
  getParentRoute: () => InteriorsRoute,
} as any)
const InteriorsFeatureWallsRoute = InteriorsFeatureWallsRouteImport.update({
  id: '/feature-walls',
  path: '/feature-walls',
  getParentRoute: () => InteriorsRoute,
} as any)
const InteriorsBedWallsRoute = InteriorsBedWallsRouteImport.update({
  id: '/bed-walls',
  path: '/bed-walls',
  getParentRoute: () => InteriorsRoute,
} as any)
const HomeFurnituresWoodenRoute = HomeFurnituresWoodenRouteImport.update({
  id: '/wooden',
  path: '/wooden',
  getParentRoute: () => HomeFurnituresRoute,
} as any)
const HomeFurnituresLaminatedRoute = HomeFurnituresLaminatedRouteImport.update({
  id: '/laminated',
  path: '/laminated',
  getParentRoute: () => HomeFurnituresRoute,
} as any)
const HomeFurnituresCushionRoute = HomeFurnituresCushionRouteImport.update({
  id: '/cushion',
  path: '/cushion',
  getParentRoute: () => HomeFurnituresRoute,
} as any)
const DoorsSlidingDoorsRoute = DoorsSlidingDoorsRouteImport.update({
  id: '/sliding-doors',
  path: '/sliding-doors',
  getParentRoute: () => DoorsRoute,
} as any)
const DoorsMainDoorsRoute = DoorsMainDoorsRouteImport.update({
  id: '/main-doors',
  path: '/main-doors',
  getParentRoute: () => DoorsRoute,
} as any)
const DoorsEngineeredDoorsRoute = DoorsEngineeredDoorsRouteImport.update({
  id: '/engineered-doors',
  path: '/engineered-doors',
  getParentRoute: () => DoorsRoute,
} as any)
const DoorsBedBathroomDoorsRoute = DoorsBedBathroomDoorsRouteImport.update({
  id: '/bed-bathroom-doors',
  path: '/bed-bathroom-doors',
  getParentRoute: () => DoorsRoute,
} as any)
const DesignSubcategoryProductRoute =
  DesignSubcategoryProductRouteImport.update({
    id: '/design/$subcategory/$product',
    path: '/design/$subcategory/$product',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminBootstrapRoute = ApiPublicAdminBootstrapRouteImport.update({
  id: '/api/public/admin-bootstrap',
  path: '/api/public/admin-bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteImageSplatRoute = ApiPublicSiteImageSplatRouteImport.update({
  id: '/api/public/site-image/$',
  path: '/api/public/site-image/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/doors': typeof DoorsRouteWithChildren
  '/faq': typeof FaqRoute
  '/home-furnitures': typeof HomeFurnituresRouteWithChildren
  '/interiors': typeof InteriorsRouteWithChildren
  '/kitchen-accessories': typeof KitchenAccessoriesRoute
  '/kitchen-appliances': typeof KitchenAppliancesRouteWithChildren
  '/kitchens': typeof KitchensRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wardrobe-accessories': typeof WardrobeAccessoriesRoute
  '/wardrobes': typeof WardrobesRouteWithChildren
  '/doors/bed-bathroom-doors': typeof DoorsBedBathroomDoorsRoute
  '/doors/engineered-doors': typeof DoorsEngineeredDoorsRoute
  '/doors/main-doors': typeof DoorsMainDoorsRoute
  '/doors/sliding-doors': typeof DoorsSlidingDoorsRoute
  '/home-furnitures/cushion': typeof HomeFurnituresCushionRoute
  '/home-furnitures/laminated': typeof HomeFurnituresLaminatedRoute
  '/home-furnitures/wooden': typeof HomeFurnituresWoodenRoute
  '/interiors/bed-walls': typeof InteriorsBedWallsRoute
  '/interiors/feature-walls': typeof InteriorsFeatureWallsRoute
  '/interiors/media-walls': typeof InteriorsMediaWallsRoute
  '/interiors/wooden-flooring': typeof InteriorsWoodenFlooringRoute
  '/kitchen-appliances/bosch': typeof KitchenAppliancesBoschRoute
  '/kitchen-appliances/fotile': typeof KitchenAppliancesFotileRoute
  '/kitchen-appliances/robam': typeof KitchenAppliancesRobamRoute
  '/kitchen-appliances/vatti': typeof KitchenAppliancesVattiRoute
  '/kitchens/classic-kitchen': typeof KitchensClassicKitchenRoute
  '/kitchens/modern-kitchen': typeof KitchensModernKitchenRoute
  '/kitchens/modular-kitchen': typeof KitchensModularKitchenRoute
  '/wardrobes/aluminium-wardrobe': typeof WardrobesAluminiumWardrobeRoute
  '/wardrobes/classic-wardrobe': typeof WardrobesClassicWardrobeRoute
  '/wardrobes/walk-in-closet': typeof WardrobesWalkInClosetRoute
  '/wardrobes/wardrobe': typeof WardrobesWardrobeRoute
  '/doors/': typeof DoorsIndexRoute
  '/home-furnitures/': typeof HomeFurnituresIndexRoute
  '/interiors/': typeof InteriorsIndexRoute
  '/kitchen-appliances/': typeof KitchenAppliancesIndexRoute
  '/kitchens/': typeof KitchensIndexRoute
  '/wardrobes/': typeof WardrobesIndexRoute
  '/api/public/admin-bootstrap': typeof ApiPublicAdminBootstrapRoute
  '/design/$subcategory/$product': typeof DesignSubcategoryProductRoute
  '/api/public/site-image/$': typeof ApiPublicSiteImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/kitchen-accessories': typeof KitchenAccessoriesRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wardrobe-accessories': typeof WardrobeAccessoriesRoute
  '/doors/bed-bathroom-doors': typeof DoorsBedBathroomDoorsRoute
  '/doors/engineered-doors': typeof DoorsEngineeredDoorsRoute
  '/doors/main-doors': typeof DoorsMainDoorsRoute
  '/doors/sliding-doors': typeof DoorsSlidingDoorsRoute
  '/home-furnitures/cushion': typeof HomeFurnituresCushionRoute
  '/home-furnitures/laminated': typeof HomeFurnituresLaminatedRoute
  '/home-furnitures/wooden': typeof HomeFurnituresWoodenRoute
  '/interiors/bed-walls': typeof InteriorsBedWallsRoute
  '/interiors/feature-walls': typeof InteriorsFeatureWallsRoute
  '/interiors/media-walls': typeof InteriorsMediaWallsRoute
  '/interiors/wooden-flooring': typeof InteriorsWoodenFlooringRoute
  '/kitchen-appliances/bosch': typeof KitchenAppliancesBoschRoute
  '/kitchen-appliances/fotile': typeof KitchenAppliancesFotileRoute
  '/kitchen-appliances/robam': typeof KitchenAppliancesRobamRoute
  '/kitchen-appliances/vatti': typeof KitchenAppliancesVattiRoute
  '/kitchens/classic-kitchen': typeof KitchensClassicKitchenRoute
  '/kitchens/modern-kitchen': typeof KitchensModernKitchenRoute
  '/kitchens/modular-kitchen': typeof KitchensModularKitchenRoute
  '/wardrobes/aluminium-wardrobe': typeof WardrobesAluminiumWardrobeRoute
  '/wardrobes/classic-wardrobe': typeof WardrobesClassicWardrobeRoute
  '/wardrobes/walk-in-closet': typeof WardrobesWalkInClosetRoute
  '/wardrobes/wardrobe': typeof WardrobesWardrobeRoute
  '/doors': typeof DoorsIndexRoute
  '/home-furnitures': typeof HomeFurnituresIndexRoute
  '/interiors': typeof InteriorsIndexRoute
  '/kitchen-appliances': typeof KitchenAppliancesIndexRoute
  '/kitchens': typeof KitchensIndexRoute
  '/wardrobes': typeof WardrobesIndexRoute
  '/api/public/admin-bootstrap': typeof ApiPublicAdminBootstrapRoute
  '/design/$subcategory/$product': typeof DesignSubcategoryProductRoute
  '/api/public/site-image/$': typeof ApiPublicSiteImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/doors': typeof DoorsRouteWithChildren
  '/faq': typeof FaqRoute
  '/home-furnitures': typeof HomeFurnituresRouteWithChildren
  '/interiors': typeof InteriorsRouteWithChildren
  '/kitchen-accessories': typeof KitchenAccessoriesRoute
  '/kitchen-appliances': typeof KitchenAppliancesRouteWithChildren
  '/kitchens': typeof KitchensRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wardrobe-accessories': typeof WardrobeAccessoriesRoute
  '/wardrobes': typeof WardrobesRouteWithChildren
  '/doors/bed-bathroom-doors': typeof DoorsBedBathroomDoorsRoute
  '/doors/engineered-doors': typeof DoorsEngineeredDoorsRoute
  '/doors/main-doors': typeof DoorsMainDoorsRoute
  '/doors/sliding-doors': typeof DoorsSlidingDoorsRoute
  '/home-furnitures/cushion': typeof HomeFurnituresCushionRoute
  '/home-furnitures/laminated': typeof HomeFurnituresLaminatedRoute
  '/home-furnitures/wooden': typeof HomeFurnituresWoodenRoute
  '/interiors/bed-walls': typeof InteriorsBedWallsRoute
  '/interiors/feature-walls': typeof InteriorsFeatureWallsRoute
  '/interiors/media-walls': typeof InteriorsMediaWallsRoute
  '/interiors/wooden-flooring': typeof InteriorsWoodenFlooringRoute
  '/kitchen-appliances/bosch': typeof KitchenAppliancesBoschRoute
  '/kitchen-appliances/fotile': typeof KitchenAppliancesFotileRoute
  '/kitchen-appliances/robam': typeof KitchenAppliancesRobamRoute
  '/kitchen-appliances/vatti': typeof KitchenAppliancesVattiRoute
  '/kitchens/classic-kitchen': typeof KitchensClassicKitchenRoute
  '/kitchens/modern-kitchen': typeof KitchensModernKitchenRoute
  '/kitchens/modular-kitchen': typeof KitchensModularKitchenRoute
  '/wardrobes/aluminium-wardrobe': typeof WardrobesAluminiumWardrobeRoute
  '/wardrobes/classic-wardrobe': typeof WardrobesClassicWardrobeRoute
  '/wardrobes/walk-in-closet': typeof WardrobesWalkInClosetRoute
  '/wardrobes/wardrobe': typeof WardrobesWardrobeRoute
  '/doors/': typeof DoorsIndexRoute
  '/home-furnitures/': typeof HomeFurnituresIndexRoute
  '/interiors/': typeof InteriorsIndexRoute
  '/kitchen-appliances/': typeof KitchenAppliancesIndexRoute
  '/kitchens/': typeof KitchensIndexRoute
  '/wardrobes/': typeof WardrobesIndexRoute
  '/api/public/admin-bootstrap': typeof ApiPublicAdminBootstrapRoute
  '/design/$subcategory/$product': typeof DesignSubcategoryProductRoute
  '/api/public/site-image/$': typeof ApiPublicSiteImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/doors'
    | '/faq'
    | '/home-furnitures'
    | '/interiors'
    | '/kitchen-accessories'
    | '/kitchen-appliances'
    | '/kitchens'
    | '/login'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/wardrobe-accessories'
    | '/wardrobes'
    | '/doors/bed-bathroom-doors'
    | '/doors/engineered-doors'
    | '/doors/main-doors'
    | '/doors/sliding-doors'
    | '/home-furnitures/cushion'
    | '/home-furnitures/laminated'
    | '/home-furnitures/wooden'
    | '/interiors/bed-walls'
    | '/interiors/feature-walls'
    | '/interiors/media-walls'
    | '/interiors/wooden-flooring'
    | '/kitchen-appliances/bosch'
    | '/kitchen-appliances/fotile'
    | '/kitchen-appliances/robam'
    | '/kitchen-appliances/vatti'
    | '/kitchens/classic-kitchen'
    | '/kitchens/modern-kitchen'
    | '/kitchens/modular-kitchen'
    | '/wardrobes/aluminium-wardrobe'
    | '/wardrobes/classic-wardrobe'
    | '/wardrobes/walk-in-closet'
    | '/wardrobes/wardrobe'
    | '/doors/'
    | '/home-furnitures/'
    | '/interiors/'
    | '/kitchen-appliances/'
    | '/kitchens/'
    | '/wardrobes/'
    | '/api/public/admin-bootstrap'
    | '/design/$subcategory/$product'
    | '/api/public/site-image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/faq'
    | '/kitchen-accessories'
    | '/login'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/wardrobe-accessories'
    | '/doors/bed-bathroom-doors'
    | '/doors/engineered-doors'
    | '/doors/main-doors'
    | '/doors/sliding-doors'
    | '/home-furnitures/cushion'
    | '/home-furnitures/laminated'
    | '/home-furnitures/wooden'
    | '/interiors/bed-walls'
    | '/interiors/feature-walls'
    | '/interiors/media-walls'
    | '/interiors/wooden-flooring'
    | '/kitchen-appliances/bosch'
    | '/kitchen-appliances/fotile'
    | '/kitchen-appliances/robam'
    | '/kitchen-appliances/vatti'
    | '/kitchens/classic-kitchen'
    | '/kitchens/modern-kitchen'
    | '/kitchens/modular-kitchen'
    | '/wardrobes/aluminium-wardrobe'
    | '/wardrobes/classic-wardrobe'
    | '/wardrobes/walk-in-closet'
    | '/wardrobes/wardrobe'
    | '/doors'
    | '/home-furnitures'
    | '/interiors'
    | '/kitchen-appliances'
    | '/kitchens'
    | '/wardrobes'
    | '/api/public/admin-bootstrap'
    | '/design/$subcategory/$product'
    | '/api/public/site-image/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/doors'
    | '/faq'
    | '/home-furnitures'
    | '/interiors'
    | '/kitchen-accessories'
    | '/kitchen-appliances'
    | '/kitchens'
    | '/login'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/wardrobe-accessories'
    | '/wardrobes'
    | '/doors/bed-bathroom-doors'
    | '/doors/engineered-doors'
    | '/doors/main-doors'
    | '/doors/sliding-doors'
    | '/home-furnitures/cushion'
    | '/home-furnitures/laminated'
    | '/home-furnitures/wooden'
    | '/interiors/bed-walls'
    | '/interiors/feature-walls'
    | '/interiors/media-walls'
    | '/interiors/wooden-flooring'
    | '/kitchen-appliances/bosch'
    | '/kitchen-appliances/fotile'
    | '/kitchen-appliances/robam'
    | '/kitchen-appliances/vatti'
    | '/kitchens/classic-kitchen'
    | '/kitchens/modern-kitchen'
    | '/kitchens/modular-kitchen'
    | '/wardrobes/aluminium-wardrobe'
    | '/wardrobes/classic-wardrobe'
    | '/wardrobes/walk-in-closet'
    | '/wardrobes/wardrobe'
    | '/doors/'
    | '/home-furnitures/'
    | '/interiors/'
    | '/kitchen-appliances/'
    | '/kitchens/'
    | '/wardrobes/'
    | '/api/public/admin-bootstrap'
    | '/design/$subcategory/$product'
    | '/api/public/site-image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DoorsRoute: typeof DoorsRouteWithChildren
  FaqRoute: typeof FaqRoute
  HomeFurnituresRoute: typeof HomeFurnituresRouteWithChildren
  InteriorsRoute: typeof InteriorsRouteWithChildren
  KitchenAccessoriesRoute: typeof KitchenAccessoriesRoute
  KitchenAppliancesRoute: typeof KitchenAppliancesRouteWithChildren
  KitchensRoute: typeof KitchensRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WardrobeAccessoriesRoute: typeof WardrobeAccessoriesRoute
  WardrobesRoute: typeof WardrobesRouteWithChildren
  ApiPublicAdminBootstrapRoute: typeof ApiPublicAdminBootstrapRoute
  DesignSubcategoryProductRoute: typeof DesignSubcategoryProductRoute
  ApiPublicSiteImageSplatRoute: typeof ApiPublicSiteImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wardrobes': {
      id: '/wardrobes'
      path: '/wardrobes'
      fullPath: '/wardrobes'
      preLoaderRoute: typeof WardrobesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wardrobe-accessories': {
      id: '/wardrobe-accessories'
      path: '/wardrobe-accessories'
      fullPath: '/wardrobe-accessories'
      preLoaderRoute: typeof WardrobeAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchens': {
      id: '/kitchens'
      path: '/kitchens'
      fullPath: '/kitchens'
      preLoaderRoute: typeof KitchensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-appliances': {
      id: '/kitchen-appliances'
      path: '/kitchen-appliances'
      fullPath: '/kitchen-appliances'
      preLoaderRoute: typeof KitchenAppliancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-accessories': {
      id: '/kitchen-accessories'
      path: '/kitchen-accessories'
      fullPath: '/kitchen-accessories'
      preLoaderRoute: typeof KitchenAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interiors': {
      id: '/interiors'
      path: '/interiors'
      fullPath: '/interiors'
      preLoaderRoute: typeof InteriorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-furnitures': {
      id: '/home-furnitures'
      path: '/home-furnitures'
      fullPath: '/home-furnitures'
      preLoaderRoute: typeof HomeFurnituresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doors': {
      id: '/doors'
      path: '/doors'
      fullPath: '/doors'
      preLoaderRoute: typeof DoorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wardrobes/': {
      id: '/wardrobes/'
      path: '/'
      fullPath: '/wardrobes/'
      preLoaderRoute: typeof WardrobesIndexRouteImport
      parentRoute: typeof WardrobesRoute
    }
    '/kitchens/': {
      id: '/kitchens/'
      path: '/'
      fullPath: '/kitchens/'
      preLoaderRoute: typeof KitchensIndexRouteImport
      parentRoute: typeof KitchensRoute
    }
    '/kitchen-appliances/': {
      id: '/kitchen-appliances/'
      path: '/'
      fullPath: '/kitchen-appliances/'
      preLoaderRoute: typeof KitchenAppliancesIndexRouteImport
      parentRoute: typeof KitchenAppliancesRoute
    }
    '/interiors/': {
      id: '/interiors/'
      path: '/'
      fullPath: '/interiors/'
      preLoaderRoute: typeof InteriorsIndexRouteImport
      parentRoute: typeof InteriorsRoute
    }
    '/home-furnitures/': {
      id: '/home-furnitures/'
      path: '/'
      fullPath: '/home-furnitures/'
      preLoaderRoute: typeof HomeFurnituresIndexRouteImport
      parentRoute: typeof HomeFurnituresRoute
    }
    '/doors/': {
      id: '/doors/'
      path: '/'
      fullPath: '/doors/'
      preLoaderRoute: typeof DoorsIndexRouteImport
      parentRoute: typeof DoorsRoute
    }
    '/wardrobes/wardrobe': {
      id: '/wardrobes/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobes/wardrobe'
      preLoaderRoute: typeof WardrobesWardrobeRouteImport
      parentRoute: typeof WardrobesRoute
    }
    '/wardrobes/walk-in-closet': {
      id: '/wardrobes/walk-in-closet'
      path: '/walk-in-closet'
      fullPath: '/wardrobes/walk-in-closet'
      preLoaderRoute: typeof WardrobesWalkInClosetRouteImport
      parentRoute: typeof WardrobesRoute
    }
    '/wardrobes/classic-wardrobe': {
      id: '/wardrobes/classic-wardrobe'
      path: '/classic-wardrobe'
      fullPath: '/wardrobes/classic-wardrobe'
      preLoaderRoute: typeof WardrobesClassicWardrobeRouteImport
      parentRoute: typeof WardrobesRoute
    }
    '/wardrobes/aluminium-wardrobe': {
      id: '/wardrobes/aluminium-wardrobe'
      path: '/aluminium-wardrobe'
      fullPath: '/wardrobes/aluminium-wardrobe'
      preLoaderRoute: typeof WardrobesAluminiumWardrobeRouteImport
      parentRoute: typeof WardrobesRoute
    }
    '/kitchens/modular-kitchen': {
      id: '/kitchens/modular-kitchen'
      path: '/modular-kitchen'
      fullPath: '/kitchens/modular-kitchen'
      preLoaderRoute: typeof KitchensModularKitchenRouteImport
      parentRoute: typeof KitchensRoute
    }
    '/kitchens/modern-kitchen': {
      id: '/kitchens/modern-kitchen'
      path: '/modern-kitchen'
      fullPath: '/kitchens/modern-kitchen'
      preLoaderRoute: typeof KitchensModernKitchenRouteImport
      parentRoute: typeof KitchensRoute
    }
    '/kitchens/classic-kitchen': {
      id: '/kitchens/classic-kitchen'
      path: '/classic-kitchen'
      fullPath: '/kitchens/classic-kitchen'
      preLoaderRoute: typeof KitchensClassicKitchenRouteImport
      parentRoute: typeof KitchensRoute
    }
    '/kitchen-appliances/vatti': {
      id: '/kitchen-appliances/vatti'
      path: '/vatti'
      fullPath: '/kitchen-appliances/vatti'
      preLoaderRoute: typeof KitchenAppliancesVattiRouteImport
      parentRoute: typeof KitchenAppliancesRoute
    }
    '/kitchen-appliances/robam': {
      id: '/kitchen-appliances/robam'
      path: '/robam'
      fullPath: '/kitchen-appliances/robam'
      preLoaderRoute: typeof KitchenAppliancesRobamRouteImport
      parentRoute: typeof KitchenAppliancesRoute
    }
    '/kitchen-appliances/fotile': {
      id: '/kitchen-appliances/fotile'
      path: '/fotile'
      fullPath: '/kitchen-appliances/fotile'
      preLoaderRoute: typeof KitchenAppliancesFotileRouteImport
      parentRoute: typeof KitchenAppliancesRoute
    }
    '/kitchen-appliances/bosch': {
      id: '/kitchen-appliances/bosch'
      path: '/bosch'
      fullPath: '/kitchen-appliances/bosch'
      preLoaderRoute: typeof KitchenAppliancesBoschRouteImport
      parentRoute: typeof KitchenAppliancesRoute
    }
    '/interiors/wooden-flooring': {
      id: '/interiors/wooden-flooring'
      path: '/wooden-flooring'
      fullPath: '/interiors/wooden-flooring'
      preLoaderRoute: typeof InteriorsWoodenFlooringRouteImport
      parentRoute: typeof InteriorsRoute
    }
    '/interiors/media-walls': {
      id: '/interiors/media-walls'
      path: '/media-walls'
      fullPath: '/interiors/media-walls'
      preLoaderRoute: typeof InteriorsMediaWallsRouteImport
      parentRoute: typeof InteriorsRoute
    }
    '/interiors/feature-walls': {
      id: '/interiors/feature-walls'
      path: '/feature-walls'
      fullPath: '/interiors/feature-walls'
      preLoaderRoute: typeof InteriorsFeatureWallsRouteImport
      parentRoute: typeof InteriorsRoute
    }
    '/interiors/bed-walls': {
      id: '/interiors/bed-walls'
      path: '/bed-walls'
      fullPath: '/interiors/bed-walls'
      preLoaderRoute: typeof InteriorsBedWallsRouteImport
      parentRoute: typeof InteriorsRoute
    }
    '/home-furnitures/wooden': {
      id: '/home-furnitures/wooden'
      path: '/wooden'
      fullPath: '/home-furnitures/wooden'
      preLoaderRoute: typeof HomeFurnituresWoodenRouteImport
      parentRoute: typeof HomeFurnituresRoute
    }
    '/home-furnitures/laminated': {
      id: '/home-furnitures/laminated'
      path: '/laminated'
      fullPath: '/home-furnitures/laminated'
      preLoaderRoute: typeof HomeFurnituresLaminatedRouteImport
      parentRoute: typeof HomeFurnituresRoute
    }
    '/home-furnitures/cushion': {
      id: '/home-furnitures/cushion'
      path: '/cushion'
      fullPath: '/home-furnitures/cushion'
      preLoaderRoute: typeof HomeFurnituresCushionRouteImport
      parentRoute: typeof HomeFurnituresRoute
    }
    '/doors/sliding-doors': {
      id: '/doors/sliding-doors'
      path: '/sliding-doors'
      fullPath: '/doors/sliding-doors'
      preLoaderRoute: typeof DoorsSlidingDoorsRouteImport
      parentRoute: typeof DoorsRoute
    }
    '/doors/main-doors': {
      id: '/doors/main-doors'
      path: '/main-doors'
      fullPath: '/doors/main-doors'
      preLoaderRoute: typeof DoorsMainDoorsRouteImport
      parentRoute: typeof DoorsRoute
    }
    '/doors/engineered-doors': {
      id: '/doors/engineered-doors'
      path: '/engineered-doors'
      fullPath: '/doors/engineered-doors'
      preLoaderRoute: typeof DoorsEngineeredDoorsRouteImport
      parentRoute: typeof DoorsRoute
    }
    '/doors/bed-bathroom-doors': {
      id: '/doors/bed-bathroom-doors'
      path: '/bed-bathroom-doors'
      fullPath: '/doors/bed-bathroom-doors'
      preLoaderRoute: typeof DoorsBedBathroomDoorsRouteImport
      parentRoute: typeof DoorsRoute
    }
    '/design/$subcategory/$product': {
      id: '/design/$subcategory/$product'
      path: '/design/$subcategory/$product'
      fullPath: '/design/$subcategory/$product'
      preLoaderRoute: typeof DesignSubcategoryProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-bootstrap': {
      id: '/api/public/admin-bootstrap'
      path: '/api/public/admin-bootstrap'
      fullPath: '/api/public/admin-bootstrap'
      preLoaderRoute: typeof ApiPublicAdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-image/$': {
      id: '/api/public/site-image/$'
      path: '/api/public/site-image/$'
      fullPath: '/api/public/site-image/$'
      preLoaderRoute: typeof ApiPublicSiteImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DoorsRouteChildren {
  DoorsBedBathroomDoorsRoute: typeof DoorsBedBathroomDoorsRoute
  DoorsEngineeredDoorsRoute: typeof DoorsEngineeredDoorsRoute
  DoorsMainDoorsRoute: typeof DoorsMainDoorsRoute
  DoorsSlidingDoorsRoute: typeof DoorsSlidingDoorsRoute
  DoorsIndexRoute: typeof DoorsIndexRoute
}

const DoorsRouteChildren: DoorsRouteChildren = {
  DoorsBedBathroomDoorsRoute: DoorsBedBathroomDoorsRoute,
  DoorsEngineeredDoorsRoute: DoorsEngineeredDoorsRoute,
  DoorsMainDoorsRoute: DoorsMainDoorsRoute,
  DoorsSlidingDoorsRoute: DoorsSlidingDoorsRoute,
  DoorsIndexRoute: DoorsIndexRoute,
}

const DoorsRouteWithChildren = DoorsRoute._addFileChildren(DoorsRouteChildren)

interface HomeFurnituresRouteChildren {
  HomeFurnituresCushionRoute: typeof HomeFurnituresCushionRoute
  HomeFurnituresLaminatedRoute: typeof HomeFurnituresLaminatedRoute
  HomeFurnituresWoodenRoute: typeof HomeFurnituresWoodenRoute
  HomeFurnituresIndexRoute: typeof HomeFurnituresIndexRoute
}

const HomeFurnituresRouteChildren: HomeFurnituresRouteChildren = {
  HomeFurnituresCushionRoute: HomeFurnituresCushionRoute,
  HomeFurnituresLaminatedRoute: HomeFurnituresLaminatedRoute,
  HomeFurnituresWoodenRoute: HomeFurnituresWoodenRoute,
  HomeFurnituresIndexRoute: HomeFurnituresIndexRoute,
}

const HomeFurnituresRouteWithChildren = HomeFurnituresRoute._addFileChildren(
  HomeFurnituresRouteChildren,
)

interface InteriorsRouteChildren {
  InteriorsBedWallsRoute: typeof InteriorsBedWallsRoute
  InteriorsFeatureWallsRoute: typeof InteriorsFeatureWallsRoute
  InteriorsMediaWallsRoute: typeof InteriorsMediaWallsRoute
  InteriorsWoodenFlooringRoute: typeof InteriorsWoodenFlooringRoute
  InteriorsIndexRoute: typeof InteriorsIndexRoute
}

const InteriorsRouteChildren: InteriorsRouteChildren = {
  InteriorsBedWallsRoute: InteriorsBedWallsRoute,
  InteriorsFeatureWallsRoute: InteriorsFeatureWallsRoute,
  InteriorsMediaWallsRoute: InteriorsMediaWallsRoute,
  InteriorsWoodenFlooringRoute: InteriorsWoodenFlooringRoute,
  InteriorsIndexRoute: InteriorsIndexRoute,
}

const InteriorsRouteWithChildren = InteriorsRoute._addFileChildren(
  InteriorsRouteChildren,
)

interface KitchenAppliancesRouteChildren {
  KitchenAppliancesBoschRoute: typeof KitchenAppliancesBoschRoute
  KitchenAppliancesFotileRoute: typeof KitchenAppliancesFotileRoute
  KitchenAppliancesRobamRoute: typeof KitchenAppliancesRobamRoute
  KitchenAppliancesVattiRoute: typeof KitchenAppliancesVattiRoute
  KitchenAppliancesIndexRoute: typeof KitchenAppliancesIndexRoute
}

const KitchenAppliancesRouteChildren: KitchenAppliancesRouteChildren = {
  KitchenAppliancesBoschRoute: KitchenAppliancesBoschRoute,
  KitchenAppliancesFotileRoute: KitchenAppliancesFotileRoute,
  KitchenAppliancesRobamRoute: KitchenAppliancesRobamRoute,
  KitchenAppliancesVattiRoute: KitchenAppliancesVattiRoute,
  KitchenAppliancesIndexRoute: KitchenAppliancesIndexRoute,
}

const KitchenAppliancesRouteWithChildren =
  KitchenAppliancesRoute._addFileChildren(KitchenAppliancesRouteChildren)

interface KitchensRouteChildren {
  KitchensClassicKitchenRoute: typeof KitchensClassicKitchenRoute
  KitchensModernKitchenRoute: typeof KitchensModernKitchenRoute
  KitchensModularKitchenRoute: typeof KitchensModularKitchenRoute
  KitchensIndexRoute: typeof KitchensIndexRoute
}

const KitchensRouteChildren: KitchensRouteChildren = {
  KitchensClassicKitchenRoute: KitchensClassicKitchenRoute,
  KitchensModernKitchenRoute: KitchensModernKitchenRoute,
  KitchensModularKitchenRoute: KitchensModularKitchenRoute,
  KitchensIndexRoute: KitchensIndexRoute,
}

const KitchensRouteWithChildren = KitchensRoute._addFileChildren(
  KitchensRouteChildren,
)

interface WardrobesRouteChildren {
  WardrobesAluminiumWardrobeRoute: typeof WardrobesAluminiumWardrobeRoute
  WardrobesClassicWardrobeRoute: typeof WardrobesClassicWardrobeRoute
  WardrobesWalkInClosetRoute: typeof WardrobesWalkInClosetRoute
  WardrobesWardrobeRoute: typeof WardrobesWardrobeRoute
  WardrobesIndexRoute: typeof WardrobesIndexRoute
}

const WardrobesRouteChildren: WardrobesRouteChildren = {
  WardrobesAluminiumWardrobeRoute: WardrobesAluminiumWardrobeRoute,
  WardrobesClassicWardrobeRoute: WardrobesClassicWardrobeRoute,
  WardrobesWalkInClosetRoute: WardrobesWalkInClosetRoute,
  WardrobesWardrobeRoute: WardrobesWardrobeRoute,
  WardrobesIndexRoute: WardrobesIndexRoute,
}

const WardrobesRouteWithChildren = WardrobesRoute._addFileChildren(
  WardrobesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DoorsRoute: DoorsRouteWithChildren,
  FaqRoute: FaqRoute,
  HomeFurnituresRoute: HomeFurnituresRouteWithChildren,
  InteriorsRoute: InteriorsRouteWithChildren,
  KitchenAccessoriesRoute: KitchenAccessoriesRoute,
  KitchenAppliancesRoute: KitchenAppliancesRouteWithChildren,
  KitchensRoute: KitchensRouteWithChildren,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WardrobeAccessoriesRoute: WardrobeAccessoriesRoute,
  WardrobesRoute: WardrobesRouteWithChildren,
  ApiPublicAdminBootstrapRoute: ApiPublicAdminBootstrapRoute,
  DesignSubcategoryProductRoute: DesignSubcategoryProductRoute,
  ApiPublicSiteImageSplatRoute: ApiPublicSiteImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
